### PR TITLE
RC/Bun - Testing bun features as package manager and runtime for projects as a default solution

### PR DESCRIPTION
**Pull request by devmozao**
All script commands are working as expected, but bun is installed per homebrew. I'm running with win/ws2 with debian.

I tried to install bun locally on the project and run commands from there - in order to force the user to use bun, but without giving him the effort to install bun itself and ease the learning curve - but got some conflicts when running command scripts.

Other point that didn't work as expected: the `--bun` flag.

When I run a command script as `bun run --bun dev`, it works as expected. When I put the `--bun` flag inside the script, let's say `"dev": "--bun vite --host",` and run `bun dev`, it doesn't work as expected, unfortunatelly. I think we should be able to use the flag on the scripts, so on your daily job, all people that works on the project, doesn't have to remember to have to use the flag, so it's a better DX overall. Also putting the flag at the end of the flag, also doesn't do.

Besides that: works like a charm.

### CODE REVIEW

**Comment by raisiqueira** [comment]
CI running in 16s 🤯 

CleanShot 2024-01-26 at 17 55 12

**Comment by raisiqueira** [comment]
LFGT 🚀

**Review by raisiqueira — APPROVED** [review]

**Comment by luigieai** [comment]
Just solved a quick merge conflict, besides that

LGTM!

**Review by luigieai — APPROVED** [review]

**Comment by devmozao** [comment]
🚀 🌋 💥 🐰

**Pull request merged**
