### PR TITLE
feat: msw basic setup

### LINKED ISSUE #19: Setup MSW in the project
Currently, the MSW is only listed as a dev dependency of the project.

Suggestion: Implement the basic MSW setup in a ViteJS project.

### PR DESCRIPTION
**Pull request by raisiqueira**
image

closes #19

### CODE REVIEW

**Comment by devMozao** [comment]
@raisiqueira I will have to review this again when I return from RJ Major, because I coudn't undestand shit of what was happening in msw config. Maybe I'm just too overwhelmed at this moment. Let's see on the days to come.

**Comment by raisiqueira** [comment]
@devMozao No worries. If you want to pairing to understand more, let's schedule an hour to do that.

**Comment by AlexcastroDev** [comment]
Hum, interesting…
Following thread 😏

**Review by devMozao — COMMENTED** [review]
LGTM! Happy 2023 everyone! 🥳🎉

**Pull request merged**
